/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e2e2e1",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-surface-variant": "#52424c",
        "secondary-fixed-dim": "#ffb59f",
        "secondary-fixed": "#ffdbd1",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1f0",
        "primary-container": "#ff90e8",
        "surface-container-high": "#e8e8e7",
        "on-error": "#ffffff",
        "primary-fixed": "#ffd7f1",
        "surface-bright": "#f9f9f8",
        "on-secondary-fixed": "#3b0a00",
        "on-tertiary": "#ffffff",
        "outline-variant": "#d6c1cd",
        "on-tertiary-fixed-variant": "#564500",
        "on-tertiary-fixed": "#231b00",
        "surface-container-low": "#f4f4f3",
        "inverse-primary": "#ffacea",
        "background": "#f9f9f8",
        "tertiary-container": "#dbb200",
        "primary-fixed-dim": "#ffacea",
        "tertiary-fixed-dim": "#eec200",
        "on-primary": "#ffffff",
        "on-surface": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "primary": "#983789",
        "surface": "#f9f9f8",
        "secondary": "#ab2e00",
        "surface-container-highest": "#e2e2e1",
        "on-primary-fixed-variant": "#7b1c70",
        "secondary-container": "#d63c00",
        "on-secondary-container": "#fffbff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#862200",
        "on-primary-container": "#7c1d71",
        "surface-container": "#eeeeed",
        "on-secondary": "#ffffff",
        "surface-tint": "#983789",
        "surface-dim": "#dadad9",
        "outline": "#84727d",
        "tertiary": "#725c00",
        "on-primary-fixed": "#390034",
        "on-tertiary-container": "#574600",
        "tertiary-fixed": "#ffe082",
        "on-background": "#1a1c1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "17px",
        "xl": "45px",
        "lg": "28px",
        "xs": "6px",
        "shadow-offset": "3px",
        "sm": "11px",
        "base": "3px",
        "border-width": "2px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "display-xl": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["13px", {"lineHeight": "1.6", "fontWeight": "500"}],
        "display-xl": ["50px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["22px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "label-bold": ["10px", {"lineHeight": "1", "fontWeight": "700"}],
        "headline-lg": ["34px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["11px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
